### ISSUE TITLE
gsub documentation is inverted

### ISSUE THREAD

**Issue by jackfoxy** [lynko/re.hoon#3]
In the readme
`(gsub:regex "(?i)hoon" "Hoon hoon hoon" "HOON")`
does not execute as expected.

Should be
```
> (gsub:regex "(?i)hoon" "HOON" "Hoon hoon hoon")
"HOON HOON HOON"
```

**Comment by jackfoxy** [comment]
This is the only function I've tried, so possibly more examples in similar situation.

**Comment by lynko** [comment]
Fixed by [#3c5e1c](https://github.com/lynko/re.hoon/commit/399b3fe89b0db4e84ba3c03705806108363c5e1c). Also how do I use git?
